;;; jbeans-theme.el --- Jbeans theme for GNU Emacs 24 (deftheme)

;; Author: Adam Olsen <arolsen@gmail.com>
;; Version: 1.0
;; Based On: ujelly by Mark Tran
;; "What do you mean, no one calls you JBeans?!  I call you JBeans!"
;; -- Wilbur

;; Original Author: Mark Tran <mark.tran@gmail.com>
;; URL: http://github.com/marktran/color-theme-ujelly
;; Package-Version: 20150807.2136
;; Version: 1.1.14

;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.
(deftheme jbeans "The jbeans color theme")

(let ((class '((class color) (min-colors 89)))
      (jbeans-fg "#cccccc")
      (jbeans-bg "#000000")
      (jbeans-blue-0 "#8fbfdc")
      (jbeans-blue-1 "#0b24fb")
      (jbeans-blue-2 "#2dfffe")
      (jbeans-blue-3 "#b2e2fe")
      (jbeans-green-0 "#99ad6a")
      (jbeans-green-1 "#447799")
      (jbeans-green-2 "#a8ff60")
      (jbeans-green-3 "#448844")
      (jbeans-green-4 "#556a32")
      (jbeans-green-5 "#335533")
      (jbeans-green-6 "#ddffdd")
      (jbeans-green-7 "#666622")
      (jbeans-green-8 "#336633")
      (jbeans-green-9 "#b6edb6")
      (jbeans-green-10 "#cceecc")
      (jbeans-green-11 "#29fd2f")
      (jbeans-grey-0 "#888888")
      (jbeans-grey-1 "#7f7f7f")
      (jbeans-grey-2 "#151515")
      (jbeans-grey-3 "#1c1c1c")
      (jbeans-grey-4 "#363636")
      (jbeans-grey-5 "#444444")
      (jbeans-grey-6 "#222222")
      (jbeans-grey-9 "#112433")
      (jbeans-grey-10 "#7f7f7f")
      (jbeans-grey-11 "#444455")
      (jbeans-grey-12 "#cccccc")
      (jbeans-grey-13 "#333344")
      (jbeans-orange-0 "#ffb964")
      (jbeans-orange-1 "#b78521")
      (jbeans-purple-0 "#8197bf")
      (jbeans-purple-1 "#474e90")
      (jbeans-purple-2 "#cd00cd")
      (jbeans-purple-3 "#540063")
      (jbeans-purple-4 "#a40073")
      (jbeans-red-0 "#cf6a4c")
      (jbeans-red-1 "#dd0093")
      (jbeans-red-2 "#de5577")
      (jbeans-red-3 "#ff73fd")
      (jbeans-red-4 "#aa4444")
      (jbeans-red-5 "#663333")
      (jbeans-red-6 "#8a3b3c")
      (jbeans-red-7 "#553333")
      (jbeans-red-8 "#fc644d")
      (jbeans-red-9 "#ffdddd")
      (jbeans-red-10 "#8a4c3b")
      (jbeans-red-11 "#eecccc")
      (jbeans-red-12 "#cb8165")
      (jbeans-red-13 "#fc0d1b")
      (jbeans-yellow-0 "#fad07a")
      (jbeans-yellow-1 "#ffff00")
      (jbeans-yellow-2 "#eeeebb")
      (jbeans-yellow-3 "#ffffcc")
      (jbeans-yellow-4 "#eddb87")
      )

      (custom-theme-set-faces
       'jbeans
       `(default ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(alchemist-test--failed-face ((,class (:foreground ,jbeans-red-0))))
       `(alchemist-test--success-face ((,class (:foreground ,jbeans-green-0))))
       `(company-preview-common ((,class (:foreground nil :background ,jbeans-purple-1))))
       `(company-scrollbar-bg ((,class (:background ,jbeans-grey-2))))
       `(company-scrollbar-fg ((,class (:background ,jbeans-grey-0))))
       `(company-tooltip ((t (:background ,jbeans-grey-2 :foreground ,jbeans-fg :weight bold))))
       `(company-tooltip-annotation ((t (:inherit company-tooltip :foreground ,jbeans-purple-0))))
       `(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
       `(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground ,jbeans-fg :underline nil :weight bold))))
       `(company-tooltip-selection ((,class (:background ,jbeans-purple-1))))
       `(compilation-error ((,class (:foreground ,jbeans-red-0))))
       `(compilation-info ((,class (:foreground ,jbeans-yellow-0))))
       `(compilation-line-number ((,class (:foreground ,jbeans-grey-0))))
       `(compilation-mode-line-exit ((,class (:foreground ,jbeans-green-0))))
       `(compilation-mode-line-fail ((,class (:foreground ,jbeans-red-0))))
       `(compilation-mode-line-run ((,class (:foreground ,jbeans-yellow-0))))
       `(neo-dir-link-face ((t (:foreground ,jbeans-purple-0))))
       `(neo-file-link-face ((t (:foreground ,jbeans-fg))))
       `(diredp-date-time ((,class (:foreground ,jbeans-green-0))))
       `(diredp-deletion ((,class (:foreground ,jbeans-red-0 :background ,jbeans-bg))))
       `(diredp-dir-heading ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-bg))))
       `(diredp-dir-priv ((,class (:foreground ,jbeans-purple-4 :background ,jbeans-bg))))
       `(diredp-exec-priv ((,class (:foreground ,jbeans-orange-1 :background ,jbeans-bg))))
       `(diredp-file-name ((,class (:foreground ,jbeans-green-10))))
       `(diredp-file-suffix ((,class (:foreground ,jbeans-grey-12))))
       `(diredp-link-priv ((,class (:foreground ,jbeans-fg))))
       `(diredp-number ((,class (:foreground ,jbeans-grey-1))))
       `(diredp-no-priv ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(diredp-rare-priv ((,class (:foreground ,jbeans-red-0 :background ,jbeans-bg))))
       `(diredp-read-priv ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-bg))))
       `(diredp-symlink ((,class (:foreground ,jbeans-purple-0))))
       `(diredp-dir-name ((,class (:foreground ,jbeans-blue-3))))
       `(diredp-write-priv ((,class (:foreground ,jbeans-purple-0 :background ,jbeans-bg))))
       `(emmet-preview-output ((,class (:background ,jbeans-purple-1))))
       `(elixir-atom-face ((,class (:foreground ,jbeans-blue-0))))
       `(erc-notice-face ((,class (:foreground ,jbeans-yellow-0))))
       `(erc-prompt-face ((,class (:foreground ,jbeans-fg))))
       `(erc-timestamp-face ((,class (:foreground ,jbeans-purple-0))))
       `(eshell-prompt ((,class (:foreground ,jbeans-red-0))))
       `(eshell-ls-directory ((,class (:weight normal :foreground ,jbeans-green-2))))
       `(eshell-ls-executable ((,class (:weight normal :foreground ,jbeans-red-0))))
       `(eshell-ls-product ((,class (:foreground ,jbeans-fg))))
       `(eshell-ls-symlink ((,class (:weight normal :foreground ,jbeans-purple-2))))
       `(evil-visual-mark-face ((,class (:weight ultra-bold :box ,jbeans-purple-0 :foreground ,jbeans-green-11))))
       `(fci-rule-color ((,class (:foreground ,jbeans-grey-4 :background ,jbeans-grey-4))))
       `(font-lock-builtin-face ((,class (:foreground ,jbeans-blue-0))))
       `(font-lock-comment-face ((,class (:slant italic :foreground ,jbeans-grey-0))))
       `(font-lock-constant-face ((,class (:foreground ,jbeans-green-1))))
       `(font-lock-doc-face ((,class (:foreground ,jbeans-green-0))))
       `(font-lock-function-name-face ((,class (:foreground ,jbeans-yellow-0))))
       `(font-lock-keyword-face ((,class (:foreground ,jbeans-purple-0))))
       `(font-lock-preprocessor-face ((,class (:foreground ,jbeans-fg))))
       `(font-lock-string-face ((,class (:foreground ,jbeans-green-0))))
       `(font-lock-type-face ((,class (:foreground ,jbeans-orange-0))))
       `(font-lock-variable-name-face ((,class (:foreground ,jbeans-red-0))))
       `(font-lock-warning-face ((,class (:foreground ,jbeans-red-1))))
       `(font-lock-regexp-grouping-construct ((t (:foreground ,jbeans-yellow-0 :bold t))))
       `(font-lock-regexp-grouping-backslash ((t (:foreground ,jbeans-red-0 :bold t))))
       `(fringe ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(header-line ((,class (:foreground ,jbeans-fg))))
       `(highlight ((t (:background ,jbeans-grey-13))))
       `(helm-visible-mark ((t (:background ,jbeans-green-5 :foreground ,jbeans-bg))))
       `(helm-buffer-file ((,class (:foreground ,jbeans-fg))))
       `(helm-buffer-process ((,class (:foreground ,jbeans-yellow-0))))
       `(helm-buffer-size ((,class (:foreground ,jbeans-fg))))
       `(helm-candidate-number ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(helm-ff-directory ((,class (:background ,jbeans-bg))))
       `(helm-ff-file ((,class (:foreground ,jbeans-fg))))
       `(helm-grep-lineno ((,class (:foreground ,jbeans-fg))))
       `(helm-match ((,class (:foreground ,jbeans-red-1 :background ,jbeans-bg))))
       `(helm-moccur-buffer ((,class (:foreground ,jbeans-yellow-0))))
       `(helm-selection ((t (:background ,jbeans-grey-13))))
       `(helm-source-header ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-grey-3))))
       `(helm-swoop-target-line-face ((,class (:foreground ,jbeans-fg :background ,jbeans-grey-4))))
       `(helm-swoop-target-word-face ((,class (:foreground ,jbeans-red-1))))
       `(hl-line ((,class (:background ,jbeans-grey-6))))
       `(isearch ((,class (:foreground ,jbeans-fg :background ,jbeans-red-1))))
       `(isearch-fail ((,class (:background ,jbeans-red-1))))
       `(ido-first-match ((,class (:foreground ,jbeans-yellow-0))))
       `(ido-only-match ((,class (:foreground ,jbeans-green-0))))
       `(ido-subdir ((,class (:foreground ,jbeans-fg))))
       `(ido-virtual ((,class (:foreground ,jbeans-purple-0))))
       `(lazy-highlight ((,class (:foreground ,jbeans-red-1 :background nil))))
       `(linum ((,class (:slant italic :foreground ,jbeans-grey-4))))
       `(ediff-even-diff-A ((t (:background ,jbeans-grey-6 :foreground ,jbeans-fg))))
       `(ediff-even-diff-B ((t (:background ,jbeans-grey-13 :foreground ,jbeans-fg))))
       `(ediff-even-diff-C ((t (:background ,jbeans-grey-11 :foreground ,jbeans-fg))))
       `(ediff-odd-diff-A ((t (:background ,jbeans-grey-6 :foreground ,jbeans-fg))))
       `(ediff-odd-diff-B ((t (:background ,jbeans-grey-13 :foreground ,jbeans-fg))))
       `(ediff-odd-diff-C ((t (:background ,jbeans-grey-5 :foreground ,jbeans-fg))))
       `(powerline-active1 ((t (:inherit mode-line :background ,jbeans-bg))))
       `(powerline-active2 ((t (:inherit mode-line :background ,jbeans-grey-13))))
       `(powerline-inactive1 ((t (:inherit mode-line :background ,jbeans-bg))))
       `(powerline-inactive2 ((t (:inherit mode-line :background ,jbeans-grey-6))))
;;;;; flycheck
       `(flycheck-error
         ((((supports :underline (:style wave)))
           (:underline (:style wave :color ,jbeans-red-1) :inherit unspecified))
          (t (:foreground ,jbeans-red-1 :weight bold :underline t))))
       `(flycheck-warning
         ((((supports :underline (:style wave)))
           (:underline (:style wave :color ,jbeans-yellow-0) :inherit unspecified))
          (t (:foreground ,jbeans-yellow-0 :weight bold :underline t))))
       `(flycheck-info
         ((((supports :underline (:style wave)))
           (:underline (:style wave :color ,jbeans-blue-2) :inherit unspecified))
          (t (:foreground ,jbeans-blue-2 :weight bold :underline t))))
       `(flycheck-fringe-error ((t (:foreground ,jbeans-red-1 :weight bold))))
       `(flycheck-fringe-warning ((t (:foreground ,jbeans-yellow-0 :weight bold))))
       `(flycheck-fringe-info ((t (:foreground ,jbeans-blue-2 :weight bold))))
       `(git-commit-comment-file ((t (:background  ,jbeans-bg :foreground  ,jbeans-fg))))
       `(git-commit-summary ((t (:background  ,jbeans-bg :foreground  ,jbeans-purple-0))))
       `(git-commit-comment-heading ((,class (:foreground ,jbeans-yellow-0))))
       `(magit-blame-heading ((t (:background ,jbeans-green-0 :foreground ,jbeans-bg))))
       `(magit-bisect-bad ((t (:foreground ,jbeans-red-6))))
       `(magit-bisect-good ((t (:foreground ,jbeans-green-4))))
       `(magit-bisect-skip ((t (:foreground ,jbeans-orange-1))))
       `(magit-blame-date ((t (:inherit magit-blame-heading))))
       `(magit-blame-hash ((t (:inherit magit-blame-heading))))
       `(magit-blame-name ((t (:inherit magit-blame-heading))))
       `(magit-blame-summary ((t (:inherit magit-blame-heading))))
       `(magit-branch-current ((t (:inherit magit-branch-local :box 1))))
       `(magit-branch-local ((t (:foreground ,jbeans-blue-3))))
       `(magit-branch-remote ((t (:foreground ,jbeans-green-0))))
       `(magit-cherry-equivalent ((t (:foreground ,jbeans-purple-2))))
       `(magit-cherry-unmatched ((t (:foreground ,jbeans-blue-2))))
       `(magit-diff-added ((t (:background ,jbeans-green-5 :foreground ,jbeans-green-6))))
       `(magit-diff-added-highlight ((t (:background ,jbeans-green-8 :foreground ,jbeans-green-10))))
       `(magit-diff-base ((t (:background ,jbeans-green-7 :foreground ,jbeans-yellow-3))))
       `(magit-diff-base-highlight ((t (:background ,jbeans-green-7 :foreground ,jbeans-yellow-2))))
       `(magit-diff-conflict-heading ((t (:inherit magit-diff-hunk-heading))))
       `(magit-diff-context ((t (:background  ,jbeans-bg :foreground  ,jbeans-fg))))
       `(magit-diff-context-highlight ((t (:background  ,jbeans-bg :foreground  ,jbeans-fg))))
       `(magit-diff-file-heading ((t (:foreground ,jbeans-purple-0 :weight bold))))
       `(magit-diff-file-heading-highlight ((t (:foreground ,jbeans-purple-0 :weight normal))))
       `(magit-diff-file-heading-selection ((t (:background  ,jbeans-bg :foreground ,jbeans-grey-12))))
       `(magit-diff-hunk-heading ((t (:background ,jbeans-bg :box ,jbeans-grey-13  :foreground ,jbeans-fg :weight bold))))
       `(magit-diff-hunk-heading-highlight ((t (:background  ,jbeans-bg :box ,jbeans-grey-0 :weight bold :foreground  ,jbeans-fg))))
       `(magit-diff-hunk-heading-selection ((t (:inherit magit-diff-hunk-heading-highlight :foreground ,jbeans-red-12))))
       `(magit-diff-lines-boundary ((t (:inherit magit-diff-lines-heading))))
       `(magit-diff-lines-heading ((t (:inherit magit-diff-hunk-heading-highlight :background ,jbeans-red-10 :foreground ,jbeans-grey-12))))
       `(magit-diff-our ((t (:inherit magit-diff-removed))))
       `(magit-diff-our-highlight ((t (:inherit magit-diff-removed-highlight))))
       `(magit-diff-removed ((t (:background ,jbeans-red-7 :foreground ,jbeans-red-9))))
       `(magit-diff-removed-highlight ((t (:background ,jbeans-red-5 :foreground ,jbeans-red-11))))
       `(magit-diff-their ((t (:inherit magit-diff-added))))
       `(magit-diff-their-highlight ((t (:inherit magit-diff-added-highlight))))
       `(magit-diff-whitespace-warning ((t (:inherit trailing-whitespace))))
       `(magit-diffstat-added ((t (:foreground ,jbeans-green-3))))
       `(magit-diffstat-removed ((t (:foreground ,jbeans-red-4))))
       `(magit-dimmed ((t (:background  ,jbeans-bg :foreground ,jbeans-grey-1))))
       `(magit-filename ((t (:foreground ,jbeans-orange-1 :weight normal))))
       `(magit-hash ((t (:foreground ,jbeans-grey-5))))
       `(magit-head ((t (:inherit magit-branch-local))))
       `(magit-header-line ((t (:inherit magit-section-heading))))
       `(magit-log-author ((t (:foreground ,jbeans-purple-0))))
       `(magit-log-date ((t (:foreground ,jbeans-green-0))))
       `(magit-log-graph ((t (:foreground ,jbeans-grey-12))))
       `(magit-popup-argument ((t (:inherit font-lock-warning-face))))
       `(magit-popup-disabled-argument ((t (:inherit shadow))))
       `(magit-popup-heading ((t (:inherit font-lock-keyword-face))))
       `(magit-popup-key ((t (:inherit font-lock-builtin-face))))
       `(magit-popup-option-value ((t (:inherit font-lock-string-face))))
       `(magit-process-ng ((t (:inherit magit-section-heading :foreground ,jbeans-red-13))))
       `(magit-process-ok ((t (:inherit magit-section-heading :foreground ,jbeans-green-11))))
       `(magit-reflog-amend ((t (:foreground ,jbeans-purple-2))))
       `(magit-reflog-checkout ((t (:foreground ,jbeans-blue-2))))
       `(magit-reflog-cherry-pick ((t (:foreground ,jbeans-green-11))))
       `(magit-reflog-commit ((t (:foreground ,jbeans-green-11))))
       `(magit-reflog-merge ((t (:foreground ,jbeans-green-11))))
       `(magit-reflog-other ((t (:foreground ,jbeans-blue-2))))
       `(magit-reflog-rebase ((t (:foreground ,jbeans-purple-2))))
       `(magit-reflog-remote ((t (:foreground ,jbeans-blue-2))))
       `(magit-reflog-reset ((t (:foreground ,jbeans-red-13))))
       `(magit-refname ((t (:background  ,jbeans-bg :foreground ,jbeans-grey-12))))
       `(magit-refname-stash ((t (:inherit magit-refname))))
       `(magit-refname-wip ((t (:inherit magit-refname))))
       `(magit-section-heading ((t (:background ,jbeans-bg :foreground ,jbeans-yellow-0))))
       `(magit-section-highlight ((t (:background ,jbeans-bg))))
       `(magit-section-secondary-heading ((t (:background ,jbeans-bg :weight bold))))
       `(magit-sequence-done ((t (:inherit magit-hash))))
       `(magit-sequence-drop ((t (:foreground ,jbeans-red-4))))
       `(magit-sequence-head ((t (:foreground ,jbeans-blue-3))))
       `(magit-sequence-onto ((t (:inherit magit-sequence-done))))
       `(magit-sequence-part ((t (:foreground ,jbeans-yellow-4))))
       `(magit-sequence-pick ((t (:inherit default))))
       `(magit-sequence-stop ((t (:foreground ,jbeans-green-9))))
       `(magit-signature-bad ((t (:foreground ,jbeans-red-13))))
       `(magit-signature-good ((t (:foreground ,jbeans-green-11))))
       `(magit-signature-untrusted ((t (:foreground ,jbeans-blue-2))))
       `(magit-tag ((t (:foreground ,jbeans-yellow-4))))
       `(match ((,class (:background ,jbeans-red-1))))
       `(minibuffer-prompt ((,class (:foreground ,jbeans-fg))))
       `(mode-line ((,class (:foreground ,jbeans-fg :background ,jbeans-grey-13))))
       `(mode-line-inactive ((,class (:foreground ,jbeans-grey-10 :background ,jbeans-grey-2))))
       `(org-checkbox ((,class (:foreground ,jbeans-green-0))))
       `(org-date ((,class (:foreground ,jbeans-purple-0))))
       `(org-done ((,class (:foreground ,jbeans-green-0))))
       `(org-level-1 ((,class (:foreground ,jbeans-red-2))))
       `(org-level-2 ((,class (:foreground ,jbeans-red-0))))
       `(org-level-3 ((,class (:foreground ,jbeans-red-0))))
       `(org-link ((,class (:foreground ,jbeans-blue-0))))
       `(org-special-keyword ((,class (:foreground ,jbeans-purple-0))))
       `(org-todo ((,class (:foreground ,jbeans-yellow-0))))
       `(region ((t (:background ,jbeans-grey-13))))
       `(shm-current-face ((,class (:background ,jbeans-grey-4))))
       `(shm-quarantine-face ((,class (:background ,jbeans-red-1))))
       `(smerge-markers ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-grey-2))))
       `(smerge-refined-change ((,class (:foreground ,jbeans-green-0))))
       `(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background ,jbeans-grey-6))))
       `(sp-show-pair-match-face ((((class color) (min-colors 89)) (:background ,jbeans-grey-5))))
       `(spaceline-evil-normal ((,class (:foreground ,jbeans-bg :background ,jbeans-orange-1))))
       `(spaceline-evil-motion ((,class (:foreground ,jbeans-bg :background ,jbeans-purple-4))))
       `(spaceline-evil-insert ((,class (:foreground ,jbeans-bg :background ,jbeans-green-3))))
       `(spaceline-evil-visual ((,class (:foreground ,jbeans-bg :background ,jbeans-grey-5))))
       `(spaceline-evil-replace ((,class (:foreground ,jbeans-bg :background ,jbeans-red-0))))
       `(spaceline-evil-emacs ((,class (:foreground ,jbeans-bg :background ,jbeans-blue-2))))
       `(spacemacs-normal-face ((,class (:foreground ,jbeans-bg :background ,jbeans-orange-1))))
       `(spacemacs-motion-face ((,class (:foreground ,jbeans-bg :background ,jbeans-purple-4))))
       `(spacemacs-insert-face ((,class (:foreground ,jbeans-bg :background ,jbeans-green-3))))
       `(spacemacs-visual-face ((,class (:foreground ,jbeans-bg :background ,jbeans-grey-5))))
       `(spacemacs-lisp-face ((,class (:foreground ,jbeans-bg :background ,jbeans-purple-2))))
       `(spacemacs-replace-face ((,class (:foreground ,jbeans-bg :background ,jbeans-red-0))))
       `(spacemacs-iedit-face ((,class (:foreground ,jbeans-bg :background ,jbeans-red-13))))
       `(spacemacs-iedit-insert-face ((,class (:foreground ,jbeans-bg :background ,jbeans-red-13))))
       `(spacemacs-evilified-face ((,class (:foreground ,jbeans-bg :background ,jbeans-green-4))))
       `(spacemacs-emacs-face ((,class (:foreground ,jbeans-bg :background ,jbeans-blue-2))))
       `(trailing-whitespace ((,class (:background ,jbeans-red-1))))
       `(vertical-border ((,class (:foreground ,jbeans-grey-11))))
       `(web-mode-builtin-face ((,class (:foreground ,jbeans-blue-0))))
       `(web-mode-html-attr-name-face ((,class (:foreground ,jbeans-purple-0))))
       `(web-mode-html-tag-face ((,class (:foreground ,jbeans-fg))))
       `(web-mode-symbol-face ((,class (:foreground ,jbeans-green-1))))
       `(whitespace-trailing ((,class (:background ,jbeans-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'jbeans)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; eval: (when (require 'rainbow-mode nil t) (rainbow-mode 1))
;; End:
;;; jbeans-theme.el ends here
